window.wordLists = {
    "most_likely_dirty": [
        "unter der Dusche pinkeln?",
        "alle Chatverläufe regelmässig löschen?",
        "auf jemanden aus der Runde masturbieren?",
        "jemandem ein Fake-Lächeln schenken?",
        "mehrere Crushes gleichzeitig haben?",
        "einen Ex stalken?",
        "einen peinlichen Fetisch haben?",
        "Sex mit dem/der Ex haben?",
        "heimlich fremdflirten?",
        "sich heimlich auf OnlyFans anmelden?",
        "im Büro einen Quickie haben wollen?",
        "eine peinliche Fantasie haben?",
        "jemanden nur wegen Sex daten?",
        "beim Sex an jemand anderen denken?",
        "ein intimes Geheimnis verraten?",
        "nachts in Insta-DMs rutschen?",
        "einen Crush auf einen Lehrer/Boss haben?",
        "etwas Wertvolles klauen?",
        "lügen, um besser dazustehen?",
        "nie zugeben, dass sie gelogen haben?",
        "jemanden nur ausnutzen?",
        "nackt Selfies machen?",
        "einen Flirt vorm Partner verstecken?",
        "beim Flirten lügen?",
        "etwas aus dem Hotel klauen?",
        "sich in jemanden aus der Runde verlieben?",
        "fremde Zahnbürsten benutzen?",
        "einen One-Night-Stand verschweigen?",
        "einen Fake-Account erstellen?",
        "sich selbst auf Google suchen?",
        "jemanden nackt stalken?",
        "sich in eine Affäre verwickeln?",
        "sich in der Öffentlichkeit selbst anfassen?",
        "beim Sex lachen?",
        "ein Sextape machen wollen?",
        "eine peinliche Sexgeschichte erzählen?",
        "jemandem erotische Nachrichten schicken?",
        "etwas beim Sex kaputt machen?",
        "im Bett so tun, als wäre es gut?",
        "einen Dildo besitzen?",
        "Sexspielzeug verschenken?",
        "an einem ungewöhnlichen Ort Sex haben wollen?",
        "eine heisse Nachricht an die falsche Person schicken?",
        "jemanden im Schlaf antatschen?",
        "einen Chat aus Versehen weiterleiten?",
        "einen heimlichen Fetisch haben?",
        "sich an einem Sexspiel versuchen?",
        "einen Crush ausnutzen?",
        "ein Rollenspiel machen wollen?",
        "einen heissen Traum von einem Freund haben?",
        "jemandem aus der Runde ein Nacktbild schicken?",
        "eine Affäre gehabt haben?",
        "einen Liebesbrief schreiben - aber nie abschicken?",
        "jemanden ghosten - nur aus Angst?",
        "beim Sex etwas extrem Peinliches sagen?",
        "beim Sex das Handy checken?",
        "jemanden beobachten - heimlich?",
        "einen peinlichen Porno schauen?",
        "auf der Arbeit Pornos schauen?",
        "sich im Spiegel beim Sex ansehen?",
        "Sex mit einem Ex-Freund der Freundin haben?",
        "jemanden aus Neid schlecht machen?",
        "einen Fake-Account zur Kontrolle nutzen?",
        "eine Sexlüge erzählen?",
        "unter Alkoholeinfluss jemandem schreiben?",
        "einen Sextraum von jemandem aus der Runde haben?",
        "sich nach dem Sex sofort verabschieden?",
        "ein Date nur für ein Geschenk annehmen?",
        "einen Freund versetzen für ein heisses Date?",
        "eine sexy Nachricht nie abschicken?",
        "ein Foto heimlich speichern?",
        "nackte Selfies auf dem Handy haben?",
        "in Unterwäsche posten - aus Versehen?",
        "sich heimlich entfolgen?",
        "jemanden sexy anstarren?",
        "eine DM nur wegen des Profils schreiben?",
        "beim Küssen den Namen verwechseln?",
        "einen One-Night-Stand googeln?",
        "jemanden aus der Runde heiss finden - und nie sagen?",
        "etwas Peinliches aus dem Mülleimer fischen?",
        "auf Social Media jemanden nachahmen?",
        "sich bei OnlyFans anmelden - aus Neugier?",
        "beim ersten Date zu direkt sein?",
        "einen Kuss erzwingen?",
        "nackt schlafen - wegen des Gefühls?",
        "ein sexuelles Missverständnis haben?",
        "jemanden wegen des Körpers daten?",
        "sich über die Körper anderer lustig machen?",
        "ein Date heimlich aufnehmen?",
        "einen falschen Namen sagen beim Sex?",
        "etwas Ekliges sexy finden?",
        "beim Flirten übertreiben?",
        "sich selbst beim Sex filmen?",
        "eine erotische Geschichte schreiben?",
        "eine peinliche Nachricht öffentlich posten?",
        "einen sexy Tanz vor dem Spiegel machen?",
        "einen peinlichen Chatverlauf zeigen?",
        "Sex mit einer Berühmtheit wollen?",
        "eine alte Flamme wieder anschreiben?",
        "etwas über Sex googeln - anonym?"
    ],
    "most_likely_drama": [
        "wegen Kleinigkeiten weinen?",
        "jeden Streit dramatisch inszenieren?",
        "im Mittelpunkt stehen wollen?",
        "eine Story grösser machen, als sie ist?",
        "alle Nachrichten deuten?",
        "ständig neue Probleme haben?",
        "bei jeder Kleinigkeit fluchen?",
        "aus Wut ghosten?",
        "sich selbst als Opfer sehen?",
        "die Gruppe mit Drama sprengen?",
        "einen „Wir müssen reden“-Moment starten?",
        "in jede Beziehung Chaos bringen?",
        "in der Insta-Story passiv-aggressiv sein?",
        "ohne Konflikt nicht glücklich sein?",
        "eine Nachricht 100-mal umformulieren?",
        "Freundschaften wegen Eifersucht beenden?",
        "ein Drama machen, wenn jemand zu spät kommt?",
        "einen Streit anfangen - und sich dann als Friedensengel geben?",
        "nach einem Streit alles löschen?",
        "heulen und schreien in einer Diskussion?",
        "nachtragend sein - aber es nie zugeben?",
        "wegen eines Blicks eine Szene machen?",
        "sich selbst ghosten, um Aufmerksamkeit zu bekommen?",
        "aus allem eine Story für Social Media machen?",
        "anderen zur Rede stellen, aber nie zuhören?",
        "Gerüchte in Umlauf bringen?",
        "öffentlich emotional werden?",
        "beim Streit weglaufen und dann schreiben?",
        "alle Ex-Partner analysieren?",
        "sich bei Kleinigkeiten zurückgewiesen fühlen?",
        "plötzlich verschwinden, wenn’s ernst wird?",
        "nie Fehler zugeben - aber Drama machen?",
        "Drama anfangen - und dann Ruhe fordern?",
        "bei einem Streit aus der Gruppe austreten?",
        "alle blockieren - und dann entblocken?",
        "nach einem Date direkt „Was sind wir?“ fragen?",
        "überreagieren, wenn jemand nicht zurückschreibt?",
        "eine Szene im Club machen?",
        "anderen Drama vorwerfen - aber selbst ausrasten?",
        "auf Insta emotional posten - und dann löschen?",
        "sich in Diskussionen selbst übertrumpfen?",
        "bei jeder Serie mitfühlen und weinen?",
        "den Partner ständig testen?",
        "eifersüchtig auf Freunde sein?",
        "bei jedem Gespräch Drama erwarten?",
        "eine belanglose Nachricht als Angriff sehen?",
        "emotional in der Öffentlichkeit eskalieren?",
        "Drama anderer kommentieren, aber selbst starten?",
        "über alte Streits nie hinwegkommen?",
        "nie Schluss machen - aber passiv-aggressiv sein?",
        "sich über ein „Okay.“ ohne Smiley aufregen?",
        "Drama machen, wenn jemand nicht sofort zurückschreibt?",
        "in Gedanken einen Streit rehearsern?",
        "eine Message löschen und dann schreiben „Egal, war eh nichts“?",
        "den Partner bei Insta stalken und dann eifersüchtig sein?",
        "einfach verschwinden, ohne etwas zu sagen?",
        "andere für Drama beschuldigen, das man selbst gestartet hat?",
        "bei einem Film weinen, der gar nicht traurig ist?",
        "im Streit mit „Mach doch, was du willst“ antworten?",
        "eine Freundschaft beenden - wegen einer Story-Reaktion?",
        "jemanden anschweigen - aus Prinzip?",
        "über Stunden einen „Punkt.“ interpretieren?",
        "den Chatverlauf fünfmal lesen - auf versteckte Bedeutungen?",
        "sich bei einem Streit selbst unterbrechen, um zu sagen, wie unfair das alles ist?",
        "nach einem Traum sauer auf jemanden sein?",
        "in der Öffentlichkeit Drama machen und dann gehen?",
        "nach einem Streit alles posten - nur nicht reden?",
        "„Ist schon okay“ sagen - und alles ist NICHT okay?",
        "eine Entschuldigung verlangen, obwohl man selbst falsch lag?",
        "Drama anfangen, wenn jemand „Haha“ statt „Hahaha“ schreibt?",
        "nach einer Story fragen: „Wieso hast du das gepostet?“?",
        "sich Drama von anderen reinziehen - und dann lästern?",
        "einen Streit aus Spass provozieren?",
        "Drama erwarten - selbst wenn alles gut läuft?",
        "einen Like von jemand anderem als Flirt deuten?",
        "Drama aufschieben - und dann explodieren?",
        "aus einer Laune heraus blockieren?",
        "„Ich hab dir das nie erzählt“ - aber es doch erzählt haben?",
        "Freundschaften testen wie eine Beziehung?",
        "ständig denken, andere reden über einen?",
        "mehr Gefühle zeigen, wenn andere zuschauen?",
        "einen Streit öffentlich austragen?",
        "bei jedem Gefühl sofort schreiben „Ich kann nicht mehr“?",
        "jemanden provozieren, um eine Reaktion zu bekommen?",
        "im Streit Dinge sagen, die man nicht meint - und nie zurücknehmen?",
        "Drama starten, weil man nicht erwähnt wurde?",
        "eine alte Nachricht wieder hochholen - mitten in einem neuen Streit?",
        "zwei Stunden für eine Insta-Caption brauchen?",
        "eine Beziehung aus Trotz beenden - und bereuen?",
        "Drama nur beenden, wenn jemand „bitte“ sagt?",
        "bei anderen Trennungen mehr weinen als bei der eigenen?",
        "ständig „Wir müssen reden“ sagen - ohne zu sagen, worüber?",
        "Drama machen, weil man in einem Gruppenbild hinten steht?",
        "wegen einer Kleinigkeit tagelang schlecht gelaunt sein?",
        "aus einer Insta-Frage ein Beziehungsdrama machen?",
        "Streit per Voice-Memo führen?",
        "jemanden ghosten, dann entblocken - dann wieder ghosten?",
        "sich über ein GIF im Chat aufregen?",
        "nie anfangen - aber immer sagen „Ich war’s nicht!“?",
        "Drama starten, weil man nicht „Guten Morgen“ geschrieben hat?"
    ],
    "most_likely_friends": [
        "sich im Streit auf die falsche Seite stellen?",
        "immer zu viel über sich selbst reden?",
        "bei Trennung direkt Partei ergreifen?",
        "den Freundeskreis regelmässig durchwechseln?",
        "dir beim Umzug helfen - und danach nie wieder melden?",
        "heimlich eifersüchtig auf dich sein?",
        "dein Date ungewollt abschrecken?",
        "nach einem Streit die Freundschaft kündigen - aber dann zurückkommen?",
        "dein peinlichstes Geheimnis ausplaudern?",
        "dich in der Öffentlichkeit verteidigen - aber privat kritisieren?",
        "sich in dein Liebesleben einmischen?",
        "dich mit jemandem verkuppeln wollen, der null passt?",
        "nur auftauchen, wenn es Drama gibt?",
        "immer den besten Rat geben - aber nie selbst danach handeln?",
        "dir aus Versehen eine falsche Info geben?",
        "beim Karaoke deinen Crush blamieren?",
        "dich vor unangenehmen Gesprächen drücken?",
        "deine Outfits ungefragt kommentieren?",
        "dir zum Geburtstag ein Last-Minute-Geschenk machen?",
        "dir treu bleiben - selbst wenn du komplett durchdrehst?",
        "ein Geheimnis nicht für sich behalten können?",
        "immer zu spät zur Verabredung kommen?",
        "dein Essen heimlich probieren?",
        "dein Selfie ohne Erlaubnis posten?",
        "deinen Crush ausfragen?",
        "sich aus Versehen in deinen Schwarm verlieben?",
        "dein Zimmer einfach umräumen?",
        "dich öffentlich blossstellen - aus Versehen?",
        "deine Ex-Beziehung analysieren wie ein Detektiv?",
        "dich bei deinen Eltern in Schutz nehmen?",
        "dich durch einen peinlichen Insta-Post trollen?",
        "dir ungefragt Tipps zum Dating geben?",
        "dein Lieblingsoutfit nachkaufen?",
        "vergessen, wie dein Haustier heisst?",
        "plötzlich ein Geheimnis mit jemand anderem teilen?",
        "sich bei Problemen ganz zurückziehen?",
        "deine Social-Media-Posts kommentieren, obwohl du es hasst?",
        "aus einem gemeinsamen Witz einen Insider mit jemand anderem machen?",
        "dich versetzen - aber mit Ausrede?",
        "deine Snacks aufessen, ohne zu fragen?",
        "bei Stress komplett abtauchen?",
        "dein Date analysieren, als wäre es ein Verhör?",
        "dein Outfit für ein Bewerbungsgespräch aussuchen wollen?",
        "dich in peinlichen Gruppenfotos markieren?",
        "dir ungefragt ein Geschenk machen - das du nicht magst?",
        "deine Playlist kritisieren?",
        "dich bei gemeinsamen Bekannten schlecht darstellen?",
        "eine Story über dich erzählen, die du verdrängt hast?",
        "plötzlich einen neuen besten Freund haben?",
        "dir ewig nicht zurückschreiben?",
        "ein peinliches Kindheitsfoto von dir posten?",
        "deinen Style kommentieren wie ein Modekritiker?",
        "deine Hobbys belächeln?",
        "dich ohne dich zu fragen für etwas anmelden?",
        "dich zu einem Event mitschleppen, das du hasst?",
        "deine Beziehung analysieren, als wäre sie ein Film?",
        "dir auf den letzten Drücker absagen?",
        "einen Insider-Joke mit dir öffentlich erklären?",
        "deine Sprachnachricht weiterleiten?",
        "dich auf einer Party ignorieren?",
        "dich für deine Vorlieben auslachen?",
        "deinen Geburtstag vergessen?",
        "dich beim Feiern ständig allein lassen?",
        "ein Selfie mit dir machen und nur sich selbst gut aussehen lassen?",
        "sich bei einem Streit nie entschuldigen?",
        "dir ständig sagen, was du falsch machst?",
        "in Gruppen ständig das Thema wechseln?",
        "einen geheimen Chat über dich starten?",
        "dich ohne Vorwarnung ghosten - und dann wieder auftauchen?",
        "deine peinlichste Story als Icebreaker erzählen?",
        "einen Streit ins Lächerliche ziehen?",
        "dein Hobby öffentlich lächerlich machen?",
        "dich auf Social Media ständig markieren?",
        "dir nie richtig zuhören - aber alles kommentieren?",
        "immer denken, im Recht zu sein?",
        "dir Komplimente geben - aber mit Unterton?",
        "sich deine Meinung nur halb merken?",
        "dich mit deinem Ex vergleichen?",
        "nur bei Langeweile schreiben?",
        "deine Probleme relativieren?",
        "auf einer Party dein Getränk austrinken?",
        "deine Grenzen nicht respektieren?",
        "dich in Stresssituationen auslachen?",
        "deinen Humor klauen?",
        "dir einen Spitznamen geben, den du hasst?",
        "bei Stress in der Gruppe Unruhe stiften?",
        "sich bei deiner Familie einschmeicheln?",
        "immer über alte Zeiten reden - aber nie über dich?",
        "deine letzte Nachricht ignorieren, aber online sein?",
        "deinen Schwarm anschreiben - just for fun?",
        "auf deinem Sofa einschlafen - regelmässig?",
        "dich auslachen, wenn du dich verredest?",
        "dich beim Date mit komischen Fragen sabotieren?",
        "dir etwas leihen und nie zurückgeben?",
        "dein Leben kommentieren wie einen Film?",
        "sich über deinen Musikgeschmack lustig machen?",
        "plötzlich mit deinem Ex befreundet sein?",
        "deinen Content ohne Erwähnung kopieren?",
        "sich in Gruppen immer wichtig machen?",
        "dir den gleichen Crush ausspannen?",
        "dich bei Gesprächen immer unterbrechen?",
        "bei Komplimenten immer widersprechen?",
        "sich dein Haustier ausleihen wollen?",
        "dir widersprechen - einfach aus Prinzip?"
    ],
    "most_likely_party": [
        "die Musik zu laut aufdrehen?",
        "auf der Tanzfläche ausrasten?",
        "einen Fremden umarmen?",
        "den DJ kritisieren?",
        "aus Versehen jemanden anflirten?",
        "den ganzen Abend nur trinken?",
        "in einem Kostüm auftauchen?",
        "beim Tanzen stolpern?",
        "am Ende aufräumen?",
        "alle zum Mitmachen überreden?",
        "den Kater des Jahrhunderts haben?",
        "die Tanzfläche eröffnen?",
        "das Motto der Party ignorieren?",
        "mit dem Barkeeper flirten?",
        "die meisten Storys posten?",
        "in der Ecke chillen statt feiern?",
        "den besten Drink mixen?",
        "einen Trinkspiel-Abend starten?",
        "sich aus dem Staub machen?",
        "am nächsten Tag nichts mehr wissen?",
        "seine Schuhe verlieren?",
        "eine Polonäse starten?",
        "auf dem Tisch tanzen?",
        "die Playlist ruinieren?",
        "einen Song zehnmal hintereinander hören wollen?",
        "die letzte Runde ausrufen?",
        "mit einem fremden Glas trinken?",
        "beim Anstossen das Glas verschütten?",
        "das erste peinliche Selfie posten?",
        "in der Badewanne landen?",
        "ein Geheimnis ausplaudern?",
        "die Party sprengen?",
        "nur für das Buffet gekommen sein?",
        "mit dem Gastgeber flirten?",
        "auf der Party einschlafen?",
        "aus Versehen eine Flasche umstossen?",
        "einen spontanen Karaoke-Battle starten?",
        "alle mit Umarmungen begrüssen?",
        "am längsten bleiben?",
        "einen neuen Spitznamen bekommen?",
        "ein Trinkspiel erfinden?",
        "mit der Deko spielen?",
        "die Musikbox mitnehmen?",
        "auf dem Heimweg verlaufen?",
        "sich im Bad einschliessen?",
        "mit dem Taxi falsch fahren?",
        "jemandem ein Lied widmen?",
        "die Einladung doppelt schicken?",
        "auf der Gästeliste fehlen?",
        "die Afterparty organisieren?",
        "mit dem Nachbarn streiten?",
        "sich über das Essen beschweren?",
        "zu laut singen?",
        "den Sekt nicht öffnen können?",
        "einen Toast halten - ungewollt?",
        "ständig tanzen, auch ohne Musik?",
        "jemandem aus Versehen was beichten?",
        "eine spontane Challenge vorschlagen?",
        "alle zum Mitternachtssnack überreden?",
        "jemanden mit Getränken volllabern?",
        "im Garten übernachten?",
        "die Polizei rufen - versehentlich?",
        "im Partnerlook erscheinen?",
        "einen peinlichen Spitznamen vergeben?",
        "sein Handy verlieren?",
        "einen Drink ausschütten - über sich selbst?",
        "das Licht ausmachen und denken, das sei cool?",
        "sich auf ein Partyspiel zu sehr einlassen?",
        "vergessen, wo man ist?",
        "jemanden duzen, der gesiezt werden will?",
        "den Gastgeber duplizieren - optisch?",
        "mit dem Sofa reden?",
        "der lauteste Lacher sein?",
        "in der falschen Wohnung landen?",
        "bei der Begrüssung ausrutschen?",
        "auf dem Balkon verschwinden?",
        "in der Küche versacken?",
        "jeden mit seinem Getränk nerven?",
        "ein spontanes Gedicht vortragen?",
        "mit dem Taxi in die falsche Richtung fahren?",
        "nachts um drei Pizza bestellen?",
        "eine Playlist crashen?",
        "zu jedem Song einen Kommentar haben?",
        "eine peinliche Tanzeinlage filmen lassen?",
        "ständig Gruppenfotos machen wollen?",
        "eine Kissenschlacht starten?",
        "einen Modetipp geben - ungewollt?",
        "den ersten Streit starten?",
        "auf dem Sofa einschlafen?",
        "versehentlich das Licht ausschalten?",
        "die Musik mit dem Handy stören?",
        "versuchen, DJ zu sein?",
        "die Getränke rationieren?",
        "bei „Wahrheit oder Pflicht“ zu ehrlich sein?",
        "die erste Runde ausgeben?",
        "zu spät kommen und alles aufhalten?",
        "einen Song falsch mitsingen - laut?",
        "am Tag danach allen schreiben „Sorry für alles“?",
        "der erste mit „Ich liebe euch alle!“ sein?",
        "die Tür nicht schliessen?",
        "am lautesten schreien?",
        "die besten Dance Moves zeigen?",
        "auf dem Balkon tanzen?",
        "die erste Person sein, die tanzt?"
    ],
    "most_likely_spicy": [
        "beim ersten Date über Sex sprechen?",
        "ein erotisches Selfie verschicken?",
        "beim Flirten zu direkt sein?",
        "einen Crush stalken?",
        "im Büro jemanden attraktiv finden?",
        "einen One-Night-Stand bereuen?",
        "einen Ex zurückwollen?",
        "einen Dreier in Erwägung ziehen?",
        "ein sexy Outfit tragen?",
        "auf einen Sugar Daddy/Mommy hoffen?",
        "beim Sex laut werden?",
        "einen Kollegen verführen?",
        "mit dem Ex befreundet bleiben wollen?",
        "während eines Dates fantasieren?",
        "ein Liebesgeheimnis haben?",
        "auf einem Dating-App-Date landen?",
        "“nur wegen dem Aussehen” daten?",
        "beim Sexting kreativ sein?",
        "Sex im Auto haben?",
        "auf einem fremden Balkon knutschen?",
        "einen Striptease aufführen?",
        "einen Sextraum über jemanden in diesem Raum haben?",
        "beim Flirten absichtlich zweideutig sein?",
        "ein Nacktbild auf dem Handy haben?",
        "mit einer fremden Person einen Kuss austauschen?",
        "einen Crush im Freundeskreis haben?",
        "während eines Videochats etwas Unangebrachtes tun?",
        "beim Date mit schmutzigen Witzen starten?",
        "jemandem einen peinlichen Liebesbrief schreiben?",
        "einen Flirt auf einer Hochzeit beginnen?",
        "einen heissen Traum erzählen?",
        "nachts jemandem eine „Was machst du gerade?“-Nachricht schreiben?",
        "aus Versehen ein intimes Bild in den falschen Chat schicken?",
        "beim Sex erwischt werden?",
        "jemanden wegen seiner Stimme attraktiv finden?",
        "einen Vibrator besitzen?",
        "einen Celebrity Crush haben?",
        "nachts nackt durch die Wohnung laufen?",
        "mit einem Kollegen oder einer Kollegin flirten?",
        "eine offene Beziehung ausprobieren?",
        "Sex im Freien haben wollen?",
        "beim Date zu schnell werden?",
        "ein sexy Kompliment machen?",
        "auf einen Flirt nicht reagieren und es später bereuen?",
        "im Schlaf stöhnen?",
        "eine erotische Geschichte schreiben?",
        "etwas im Bett googeln müssen?",
        "sich in einen Lehrer oder Chef verknallen?",
        "einen heissen Songtext mitfühlen?",
        "jemanden heimlich beobachten?",
        "beim Date absichtlich provozieren?",
        "einen Ex stalken?",
        "sich in einem Club blamieren?",
        "einen Kuss beim Wahrheit-oder-Pflicht erleben?",
        "ein Nacktbild fast auf Social Media posten?",
        "aus Spass ein Erotikspiel kaufen?",
        "sich in eine unerreichbare Person verlieben?",
        "eine Affäre haben?",
        "ein sexy Geheimnis mit sich tragen?",
        "ein verbotenes Foto machen?",
        "im falschen Moment „Ich liebe dich“ sagen?",
        "auf einen Lehrer oder eine Lehrerin stehen?",
        "einen sexy Song auf Dauerschleife hören?",
        "bei der Arbeit flirten?",
        "ein heisses Date vergessen?",
        "jemandem einen peinlichen Spitznamen geben?",
        "etwas Erotisches aus dem Internet bestellen?",
        "nachts betrunken schreiben?",
        "seinen Eltern ein peinliches Geheimnis erzählen müssen?",
        "Sex beim ersten Date haben?",
        "eine Dating-App heimlich nutzen?",
        "nachts jemanden vermissen, den man kaum kennt?",
        "jemandem mit Blicken alles sagen?",
        "einen Freund oder eine Freundin attraktiv finden?",
        "nachts schlaflos wegen eines Flirts sein?",
        "einen Sex-Podcast hören?",
        "eine heimliche Vorliebe haben?",
        "beim Küssen lachen müssen?",
        "einen peinlichen Moment beim Flirten erleben?",
        "einen Crush auf jemanden haben, der vergeben ist?",
        "einen Flirt abbrechen, weil’s zu heiss wurde?",
        "im falschen Moment an Sex denken?",
        "aus Neugier auf einen OnlyFans-Link klicken?",
        "ein erotisches Buch lesen?",
        "nachts einen Flirt wieder löschen?",
        "Sex auf einer Party in Erwägung ziehen?",
        "jemanden mit Blicken ausziehen?",
        "mit jemandem in der Sauna flirten?",
        "einen geheimen Fetisch haben?",
        "etwas Peinliches beim Date sagen?",
        "einen Flirt nicht bemerken?",
        "nach einem Kuss wegrennen wollen?",
        "einen erotischen Traum nachspielen wollen?",
        "mit jemandem auf der Arbeit rummachen wollen?",
        "ein Video mit erotischem Inhalt mögen?",
        "nachts nackt schlafen - auch bei Besuch?",
        "jemanden beim Umziehen beobachten?",
        "auf einer Party etwas zu direkt sein?",
        "beim Feiern jemanden spontan küssen?",
        "jemandem auf Instagram heimlich folgen?",
        "etwas Peinliches auf einer Dating-App schreiben?",
        "sich beim Flirten total verhaspeln?",
        "einen sexy Tanz aufführen?",
        "nachts im Chat zu viel verraten?",
        "einen heissen Traum in der Gruppe erzählen?",
        "sich an ein peinliches erstes Mal erinnern?",
        "eine erotische Nachricht an die falsche Person schicken?",
        "einen Flirt als Spiel sehen?",
        "beim ersten Treffen ein zweideutiges Geschenk mitbringen?",
        "jemandem durch Social Media nachspionieren?",
        "beim Sex an jemand anderen denken?",
        "einen heissen Traum von einem Promi haben?",
        "nachts nach jemandem googeln, der süss war?",
        "einen anzüglichen Songtext posten?",
        "ein intimes Spiel ausprobieren wollen?",
        "etwas Unangemessenes sagen und rot werden?",
        "ein peinliches Selfie verschicken?",
        "nachts jemanden anrufen und dann auflegen?",
        "im Club jemanden mit nach Hause nehmen wollen?",
        "Sex im Bad ausprobieren?",
        "einen Crush auf den Barkeeper/in haben?"
    ],
    "most_likely_wild": [
        "mit einem Fremden durchbrennen?",
        "nachts in den Pool springen?",
        "die Polizei aus Spass rufen?",
        "plötzlich kündigen?",
        "eine wilde Partynacht organisieren?",
        "eine Woche ohne Plan leben?",
        "barfuss durch die Stadt laufen?",
        "einen fremden Koffer mitnehmen?",
        "im Club auf dem Tisch tanzen?",
        "einen Scherz komplett eskalieren lassen?",
        "nachts laut im Treppenhaus singen?",
        "sich ein verrücktes Tattoo stechen lassen?",
        "versehentlich nackt im Zoom-Call erscheinen?",
        "eine Schlägerei provozieren?",
        "einen Feueralarm auslösen?",
        "aus Trotz eine neue Frisur machen?",
        "einen fremden Hund klauen - für 10 Minuten?",
        "ein Date spontan nach Las Vegas mitnehmen?",
        "eine Bar aus Versehen demolieren?",
        "sein Handy im Kühlschrank finden?",
        "nachts betrunken die Ex anrufen?",
        "im Supermarkt tanzen?",
        "aus Wut ein Handy werfen?",
        "im Fahrstuhl laut schreien?",
        "mit einem Einkaufswagen Rennen fahren?",
        "einen Club verwechseln und bleiben?",
        "nachts nackt durch die Wohnung laufen?",
        "ein fremdes Taxi klauen - aus Versehen?",
        "eine Karaoke-Performance sprengen?",
        "ein Tattoo bereuen?",
        "einen Feuerlöscher ausprobieren - ohne Grund?",
        "ein Polizeiauto antanzen?",
        "auf einer Hochzeit randalieren?",
        "ein Festival komplett nackt erleben wollen?",
        "eine Strasse mit Kreide bemalen?",
        "nachts auf dem Spielplatz feiern?",
        "ein Fahrrad mitgehen lassen - und zurückbringen?",
        "eine Schaufensterpuppe mitnehmen?",
        "sich im Club verlaufen?",
        "nachts laut Liebesbriefe rufen?",
        "eine WG-Party ruinieren?",
        "versehentlich die Polizei küssen?",
        "die Nacht auf dem Dach verbringen?",
        "sich in einem fremden Bett wiederfinden?",
        "im Restaurant auf den Tisch steigen?",
        "sich ein Nasenpiercing selbst stechen?",
        "einen Heiratsantrag im Spass machen?",
        "eine Partyeinladung faken?",
        "einen Baum umarmen und weinen?",
        "bei Rot über die Strasse tanzen?",
        "die Notausgangstür öffnen - aus Neugier?",
        "nachts ein fremdes Haus für das eigene halten?",
        "einen Koffer im Club vergessen?",
        "versehentlich bei jemand Fremdem aufwachen?",
        "nachts ein Feuerwerk zünden?",
        "eine Mülltonne als Versteck nutzen?",
        "ein Auto mit Lippenstift bemalen?",
        "eine U-Bahn-Ansage imitieren?",
        "nachts in einen Brunnen springen?",
        "einen fremden Balkon erklimmen?",
        "eine Party sprengen - ungewollt?",
        "im Supermarkt übernachten wollen?",
        "im Regen barfuss tanzen?",
        "nachts eine „Demo“ starten - allein?",
        "ein Konzert stürmen?",
        "mit einem Flamingo aufblasbar fliehen?",
        "im Museum einschlafen?",
        "versehentlich nackt aufwachen?",
        "nachts mit Freunden ein Zelt aufbauen - mitten in der Stadt?",
        "einen Verkehrspylon klauen?",
        "im Club barfuss tanzen?",
        "mitten in der Nacht laut duschen?",
        "einen Einkaufswagen mit nach Hause nehmen?",
        "bei einem Umzug in der Kiste landen?",
        "im Aufzug Karaoke singen?",
        "eine Strassenlaterne umarmen?",
        "nachts laut seine Gefühle verkünden?",
        "nachts aus Versehen fremdgehen?",
        "einen Fremden umarmen - ohne Kontext?",
        "aus einem Meeting fliehen - durchs Fenster?",
        "im Club die Musik übernehmen?",
        "versehentlich auf der Bühne landen?",
        "nachts in den Zoo einbrechen wollen?",
        "in einen Springbrunnen pinkeln?",
        "im Hotel im Bademantel rausgehen?",
        "mitten auf der Strasse tanzen?",
        "ein Taxi verwechseln - und mitfahren?",
        "nachts laut mit Tieren sprechen?",
        "einen Mitbewohner erschrecken - mit Maske?",
        "einen Streich mit echtem Blaulicht spielen?",
        "nachts laut im Park opernsingen?",
        "aus Protest nackt werden?",
        "einen Auftritt sabotieren - aus Versehen?",
        "nachts im Garten zelten - ohne Grund?",
        "eine Partyeinladung übertreiben?",
        "nachts eine Sirene nachmachen?",
        "einen Roller klauen - für 2 Minuten?",
        "im Club einschlafen?",
        "sich verlaufen - und feiern?",
        "nachts laut Liebeslieder singen?",
        "einen fremden Geburtstag crashen?",
        "die Polizei zu einer Party einladen?",
        "nachts ein Strassenschild klauen?",
        "im Kostüm einkaufen gehen?",
        "in einem Planschbecken übernachten?"
    ],
    "most_likely_classic": [
        "einen Tag lang nichts sagen?",
        "im falschen Moment laut lachen?",
        "sein Handy zu Hause vergessen?",
        "beim Filmeabend einschlafen?",
        "immer zu spät kommen?",
        "sich beim Sport verletzen?",
        "die Hausaufgaben für andere machen?",
        "den Geburtstag eines Freundes vergessen?",
        "beim Kochen alles anbrennen lassen?",
        "im Aufzug stecken bleiben?",
        "einen Promi nicht erkennen?",
        "mit dem falschen Namen ansprechen?",
        "sich verlaufen?",
        "mitten im Gespräch abschweifen?",
        "ein neues Hobby starten?",
        "ohne Navi nicht ans Ziel kommen?",
        "jedem Trinkgeld geben?",
        "sich beim Online-Shopping verklicken?",
        "Sprachnachrichten hassen?",
        "beim Spieleabend schummeln?",
        "beim Karaoke den Text vergessen?",
        "versehentlich auf „Allen antworten“ klicken?",
        "im Schlaf reden?",
        "einen peinlichen Screenshot verschicken?",
        "mit vollem Mund sprechen?",
        "einen Scherz zu ernst nehmen?",
        "mit Fremden ins Gespräch kommen?",
        "bei einem Kinderfilm weinen?",
        "den Wecker überhören?",
        "Sachen verlegen und nie wiederfinden?",
        "die Tür nicht abschliessen?",
        "versehentlich auf „Gefällt mir“ bei einem alten Foto klicken?",
        "eine WhatsApp-Nachricht an die falsche Person schicken?",
        "nach dem Smalltalk peinliche Stille erzeugen?",
        "den Einkaufswagen vergessen zurückzubringen?",
        "einen Lachflash an der falschen Stelle bekommen?",
        "die Pointe eines Witzes vergessen?",
        "beim Selfie die Augen zuhaben?",
        "sein Passwort ständig vergessen?",
        "sich auf einem Familienfoto unwohl fühlen?",
        "über sich selbst lachen?",
        "das Kleingeld verlieren?",
        "eine Pflanze eingehen lassen?",
        "den Müll rausbringen vergessen?",
        "Kaugummi unter dem Schuh kleben haben?",
        "den Lieblingspulli zu heiss waschen?",
        "versehentlich jemanden duzen, der gesiezt werden will?",
        "eine peinliche Kindergeschichte erzählen?",
        "sich im Supermarkt verlaufen?",
        "jemanden versehentlich ignorieren?",
        "im falschen Chat antworten?",
        "das Ladegerät vergessen?",
        "fünfmal denselben Pulli kaufen?",
        "sich zu viel vornehmen und nichts schaffen?",
        "vergessen, warum man in den Raum gegangen ist?",
        "im falschen Bus landen?",
        "bei einer Rede nervös werden?",
        "den ganzen Tag im Schlafanzug bleiben?",
        "mit ungeputzten Zähnen zur Tür gehen?",
        "beim Staubsaugen etwas Wichtiges einsaugen?",
        "in einem Meeting einschlafen?",
        "auf eine Spam-Mail reinfallen?",
        "beim Online-Test schummeln?",
        "sich bei einer App nicht auskennen?",
        "den Kaffee verschütten?",
        "das Datum verwechseln?",
        "auf dem Weg zur Arbeit den falschen Weg nehmen?",
        "bei „Alle ausser mir“-Fragen als Letzter übrig bleiben?",
        "versuchen, cool zu tanzen - und sich blamieren?",
        "auf einen falschen Link klicken?",
        "eine wichtige Deadline verpassen?",
        "eine Nachricht liken, die gar nicht lustig war?",
        "sich beim Namen vorstellen und sich verhaspeln?",
        "beim Videocall stumm geschaltet sein und lange reden?",
        "sein Ladekabel jemand anderem klauen?",
        "im Bus einschlafen und die Haltestelle verpassen?",
        "den Herd anlassen?",
        "seine PIN vergessen?",
        "einen Screenshot im falschen Chat teilen?",
        "im Schlaf sprechen oder schnarchen?",
        "eine Mail an den falschen Empfänger schicken?",
        "Smalltalk vermeiden?",
        "sich über ein Meme totlachen?",
        "etwas Wichtiges verschlafen?",
        "zwei verschiedene Socken tragen?",
        "beim Einkaufen die Einkaufsliste verlieren?",
        "eine Verabredung doppelt buchen?",
        "beim Sport direkt Muskelkater bekommen?",
        "leeres Geschenkpapier aufbewahren?",
        "vergessen, wo das Auto steht?",
        "aus Versehen eine Story posten?",
        "jemandem zu lange winken?",
        "mit Zahnpasta im Gesicht das Haus verlassen?",
        "mit geschlossenen Augen Selfies machen?",
        "nachts das Licht anlassen?",
        "vergessen, den Müll rauszustellen?",
        "ein anderes Passwort bei jeder Website haben?",
        "im Fahrstuhl die falsche Etage drücken?",
        "den Namen eines Lehrers vergessen?",
        "den falschen Einkauf mit nach Hause nehmen?",
        "beim Online-Kurs frühzeitig aufgeben?",
        "die Spülmaschine falsch einräumen?",
        "einen Tee vergessen und dann kalt trinken?",
        "einen Ohrwurm laut mitsingen?",
        "einen Witz erklären müssen?",
        "beim Videocall mit Pyjamahose sitzen?",
        "ständig neue Apps installieren und nie nutzen?",
        "die Fernbedienung verlieren?",
        "mit leeren Akkus rausgehen?",
        "immer denselben Hoodie tragen?",
        "ein Emoji falsch verwenden?",
        "im Meeting „Mama“ sagen?",
        "versehentlich jemanden anrufen?",
        "jemandem antworten, der gar nichts gefragt hat?",
        "den falschen Tag für ein Event im Kopf haben?",
        "den Timer stellen und trotzdem etwas anbrennen lassen?",
        "die Post ewig nicht abholen?",
        "einen Kalender führen - aber nie reinschauen?",
        "das Geburtstagsgeschenk selbst behalten wollen?",
        "bei einer Onlinebestellung die falsche Grösse wählen?",
        "auf ein Werbebanner klicken?",
        "einen falschen Namen speichern?",
        "sich zu oft verabreden und alles absagen?",
        "sein Handy im Kühlschrank vergessen?",
        "zu laut tippen beim Chatten?",
        "einen Screenshot als Story posten?",
        "versehentlich „Ich liebe dich“ schreiben?",
        "sich an der Mikrowelle erschrecken?",
        "beim Quiz die einfachste Frage falsch beantworten?",
        "beim Einschlafen den Podcast nicht ausmachen?",
        "aus Versehen laut pupsen?",
        "einen schlechten Witz immer wieder erzählen?",
        "sich bei einer Präsentation verhaspeln?",
        "einen Aufzugknopf mehrmals drücken?",
        "auf der Fernbedienung einschlafen?",
        "laut „Ja!“ sagen - und die Frage nicht kennen?",
        "im Bus denken, man ist allein - und singen?"
    ]
};