const chaos = {
  truth: [
    "Was war das Dümmste, das du je freiwillig getan hast?",
    "Was war dein chaotischstes Erlebnis mit Freunden?",
    "Wer ist die wildeste Person, die du kennst?",
    "Welches Gerücht über dich war tatsächlich wahr?",
    "Hast du schon mal etwas in Brand gesetzt - aus Versehen oder absichtlich?",
    "Was war dein schlimmster Lachanfall zur falschen Zeit?",
    "Was würdest du tun, wenn du für einen Tag keine Konsequenzen zu befürchten hättest?",
    "Welche Person hier würdest du auf keinen Fall mit in ein Chaos-Abenteuer nehmen?",
    "Was war der grö sste Schwindel, den du je durchgezogen hast?",
    "Bist du schon mal von einem Ort geflogen worden (z. B. Club, Veranstaltung)?",
    "Was würdest du mit 1.000 Euro in nur 60 Minuten anstellen?",
    "Hast du schon mal ein Gesetz gebrochen?",
    "Was war die verrückteste Nacht deines Lebens?",
    "Welcher Gegenstand aus deinem Zimmer beschreibt dein Leben am besten?",
    "Was war die unpassendste Situation, in der du laut lachen musstest?",
    "Was würdest du tun, wenn du in einem völlig fremden Land ohne Geld aufwachst?",
    "Mit wem würdest du gerne einen Tag lang das Leben tauschen?",
    "Was ist die absurdeste Ausrede, die du je benutzt hast?",
    "Hast du schon mal einen „Mutproben-Fail“ erlebt?",
    "Was war dein spontanster Trip?",
    "Was würdest du tun, wenn du plötzlich auf einer Bühne mit Mikrofon stehst?",
    "Was war der grö sste Kontrollverlust, den du je hattest?",
    "Welchen Impuls hast du mal gerade noch so unterdrückt?",
    "Welche Regel hast du zuletzt bewusst ignoriert?",
    "Was ist das Albernste, das du heimlich gerne machst?",
  ],
  dare: [
    "Lass dir von allen eine Aufgabe geben - du musst 3 davon gleichzeitig machen.",
    "Spiele „Luftgitarre“ zu einem imaginären Rockkonzert.",
    "Iss eine merkwürdige Kombination, die die Gruppe auswählt.",
    "Springe auf und tu so, als würde dein Stuhl brennen.",
    "Mach eine dramatische Slow-Motion-Action-Szene.",
    "Stelle für 60 Sekunden alles nach, was jemand aus der Runde tut.",
    "Tanze wie ein Roboter, der durchdreht - für 30 Sekunden.",
    "Sprich die nächsten 3 Minuten nur mit Geräuschen, keine echten Wörter.",
    "Lass dich mit verbundenen Augen von der Gruppe „umstylen“. ",
    "Drehe dich 10-mal im Kreis und laufe dann eine gerade Linie.",
    "Tu so, als wärst du ein wildes Tier - die Gruppe entscheidet welches.",
    "Rufe aus dem Fenster (oder laut in die Gegend): „Ich bin bereit für die Apokalypse!“",
    "Starte eine imaginäre Talkshow mit einem Gegenstand als Gast.",
    "Erzähle eine Geschichte - jedes Mal, wenn du „und“ sagen willst, springst du auf.",
    "Suche dir ein „Haustier“ (Gegenstand) und stelle es der Runde vor.",
    "Tue so, als hättest du einen unsichtbaren Freund, den du jedem vorstellst.",
    "Sprich mit einem Stuhl, als hättest du einen Beziehungsstreit.",
    "Führe einen Rap über ein völlig banales Thema auf (z. B. Zahnpasta).",
    "Gib allen in der Runde einen Superhelden-Namen und beschreibe ihre Superkraft.",
    "Laufe wie ein Pinguin und watschel im Kreis.",
    "Leg dich auf den Boden und tue so, als wärst du ein Teppich.",
    "Erfinde eine neue Sprache und sprich für 2 Minuten nur in dieser.",
    "Imitiere für eine Minute den Alarm einer Einparkhilfe.",
    "Lass dir von jemandem ein Gesicht auf den Bauch malen und rede mit Bauchstimme.",
    "Mache eine spontane Werbeanzeige für das nutzloseste Objekt in deiner Nähe.",
  ],
};

const classic = {
  truth: [
    "Was war dein peinlichstes Erlebnis?",
    "Hast du schon mal bei einem Test geschummelt?",
    "Wer ist dein aktueller Crush?",
    "Was war dein schlimmster Fehlkauf?",
    "Hast du schon mal etwas geklaut?",
    "Welche Angewohnheit findest du an dir selbst nervig?",
    "Wann hast du das letzte Mal gelogen?",
    "Was war dein letzter Google-Suchbegriff?",
    "Welche Serie oder Film findest du super, ist dir aber peinlich?",
    "Welche Person hier würdest du gerne besser kennenlernen?",
    "Was ist dein grö sster Traum?",
    "Mit welchem Promi würdest du gerne mal essen gehen?",
    "Was war dein schlimmster Flirtversuch?",
    "Hast du schon mal einen Liebesbrief geschrieben?",
    "Was ist deine grö sste Angst?",
    "Was würdest du an deinem Leben sofort ändern?",
    "Wer hier hat deiner Meinung nach den besten Style?",
    "Was war das Mutigste, das du je getan hast?",
    "Hast du schon mal eine wichtige Nachricht absichtlich ignoriert?",
    "Was war dein erster Eindruck von der Person rechts von dir?",
    "Was ist dein Guilty Pleasure?",
    "Was ist das Kindischste, das du heute noch gerne machst?",
    "Folgst du Hannes und Jeremy auf TikTok?",
    "Magst du Hannes oder Jeremy mehr?",
    "Wie viele Jungs/Mädchen hast du bisher geküsst?",
    "Bist du im Moment verliebt?",
    "Hast du schon mal mit einer Frau/einem Mann rumgemacht?",
    "Was war dein letzter Traum, an den du dich erinnerst?",
    "Hast du schon mal etwas geklaut? Wenn ja, was?",
    "Was war dein schönstes Date?",
    "Was war dein schlimmstes Date?",
    "Wen in der Runde findest du am interessantesten?",
    "Mit wem in der Runde würdest du am liebsten einen Urlaub verbringen?",
    "Hast du schon mal eine Straftat begangen?",
    "Mit wem hattest du deinen ersten Kuss?",
    "Welches Tier wärst du am liebsten?",
    "Hast du schon mal illegale Drogen genommen?",
    "Wen in der Runde findest du am attraktivsten?",
    "Wonach hast du als Letztes gegoogelt?",
    "Wer in der Runde ist am besten angezogen und warum?",
    "Welches ist dein aktuelles Lieblingslied?",
    "Von wem hast du deinen letzten Korb bekommen?",
    "Hast du schon mal auf dem Klo telefoniert?",
    "Habt ihr schon mal heimlich ein TikTok gepostet und es gelöscht, weil es wenig Aufrufe hatte?",
    "Was war das Gemeinste, was du je getan hast?",
    "Was war das Kriminellste, was du je getan hast?",
    "Hast du schon mal sexy Bilder von dir verschickt?",
    "Würdest du mit jemandem knutschen, den du gerade erst kennengelernt hast?",
    "Was findest du an dir am sexiesten?",
    "Wofür hast du dich in letzter Zeit geschämt?",
    "Worauf guckst du zuerst, wenn du jemanden kennenlernst?",
    "Wie kann man dich am schnellsten von sich begeistern?",
    "Wer in der Runde hat die schönsten Lippen?",
    "Wer in der Runde hat den schönsten Hintern?",
    "Wie sieht dein Traumdate aus?",
    "Mit wem in der Runde würdest du gerne für einen Tag das Leben tauschen?",
    "Welche Körperstellen rasierst du regelmä ssig?",
    "Was war deine letzte Lüge?",
    "Welches Abenteuer würdest du gerne noch erleben?",
    "Hast du schon mal jemanden betrogen?",
    "Was würdest du an deinem Körper verändern, wenn du könntest?",
    "Was würdest du machen, wenn du nur noch eine Stunde zu leben hättest?",
    "Was turnt dich bei Frauen/Männern besonders an?",
    "Was war der grö sste Fehler deines Lebens?",
    "Wie viele Menschen hast du schon geküsst?",
    "Welcher ist dein Lieblings-Song?",
    "Wann hattest du das letzte Mal einen Hangover?",
    "In wen bist du verliebt?",
    "Was war das Peinlichste, das dir jemals passiert ist?",
    "Hast du schon einmal jemanden heimlich beobachtet?",
    "Was ist das Verrückteste, das du je getan hast?",
    "Welche Person in dieser Runde würdest du am liebsten küssen?",
    "Was ist das Seltsamste, was du jemals gegessen hast?",
    "Welches war dein schlimmster Liebeskummer?",
    "Was ist das Merkwürdigste, das du je über jemanden gedacht hast?",
    "Welches ist dein grö sstes unerfülltes Ziel oder deine grö sste unerfüllte Fantasie?",
    "Hast du schon einmal absichtlich jemanden verletzt?",
    "Was ist das Peinlichste, was deine Eltern je vor dir getan haben?",
    "Was ist das Romantischste, was du jemals für jemanden getan hast?",
    "Hast du schon einmal eine Beziehung geheim gehalten?",
    "Was war der verrückteste Ort, an dem du jemals geküsst hast?",
    "Würdest du eher die Wahrheit sagen oder eine Pflicht erfüllen, die dich in Verlegenheit bringen würde?",
    "Was ist das Längste, was du jemals ohne Duschen ausgehalten hast?",
    "Hast du schon einmal in der Öffentlichkeit gefurzt und es jemand anderem in die Schuhe geschoben?",
    "Wann hattest du das letzte Mal einen Wutanfall und warum?",
    "Welche Person in dieser Runde würdest du am ehesten daten?",
    "Was ist das Seltsamste, was du jemals im Internet recherchiert hast?",
    "Hast du schon einmal über eine Person gelästert, die gerade im Raum war?",
    "Was war der aufregendste Moment deines Lebens?",
    "Hast du schon einmal jemanden online gestalkt?",
    "Was war das Lustigste, das du jemals erlebt hast?",
    "Würdest du lieber dein peinlichstes Foto im Internet teilen oder dein dunkelstes Geheimnis preisgeben?",
    "Was ist das Schlimmste, was du je jemandem angetan hast?",
    "Wovon träumst du, wenn du nachts schlafen gehst?",
    "Hast du schon einmal etwas getan, wofür du dich sehr geschämt hast?",
    "Was war das Verrückteste, das du jemals für Geld getan hast?",
    "Welche Eigenschaft an dir wünschst du dir, dass sie stärker ausgeprägt ist?",
    "Was war der ungewöhnlichste Ort, an dem du jemals gepinkelt hast?",
    "Hast du schon einmal etwas gestohlen, das du jetzt bereust?",
    "Was war das Letzte, wofür du geweint hast?",
    "Hast du schon einmal absichtlich jemanden belogen, den du liebst?",
    "Was war das Dümmste, was du jemals getan hast?",
    "Würdest du eher die Wahrheit sagen oder eine peinliche Aufgabe erfüllen?",
    "Hast du schon einmal überlegt, ob du eine andere sexuelle Orientierung hast?",
    "Was ist das Schlimmste, was dir jemals passiert ist?",
    "Welche Person in dieser Runde findest du am attraktivsten?",
    "Hast du schon einmal etwas im Geschäft probiert und nicht bezahlt?",
    "Was ist das Gemeinste, was dir jemals jemand angetan hat?",
    "Welche Eigenschaft an dir wünschst du dir, dass sie schwächer ausgeprägt ist?",
    "Hast du schon einmal etwas Peinliches über dich selbst im Internet veröffentlicht?",
    "Was war der grö sste Streit, den du jemals mit jemandem hattest?",
    "Würdest du lieber die Wahrheit sagen oder eine Pflicht erfüllen, bei der du dich übergeben musst?",
    "Hast du schon einmal überlegt, mit jemandem Schluss zu machen, den du liebst?",
    "Was ist das Peinlichste, was dir je in der Schule passiert ist?",
    "Hast du schon einmal einen Liebesbrief geschrieben und nicht abgeschickt?",
    "Was war das Verrückteste, was du je im Namen der Liebe getan hast?",
    "Welche Person in dieser Runde würdest du am ehesten heiraten?",
    "Hast du schon einmal etwas Illegales getan, wofür du nicht erwischt wurdest?",
    "Wer hat den höchsten IQ in der Runde?",
    "Was kannst du besser als alle anderen hier?",
    "Wer würde am längsten eine Zombie-Apokalypse überleben?",
    "Wie oft lügst du am Tag?",
    "Wie oft schaust du täglich in den Spiegel?",
    "Wie würdest du dein Aussehen auf einer Skala von 1 bis 10 bewerten?",
    "Wie würdest du deinen Charakter auf einer Skala von 1 bis 10 bewerten?",
    "Ist Küssen für dich bereits fremdgehen?",
    "Was ist der eigentlich unschlimmste Grund, für den du Schluss machen würdest?",
    "Welche Schönheits-OP würdest du machen lassen, wenn sie perfekt ausgeführt werden würde?",
    "Wer kommt dir als Erstes in den Kopf, wenn du das Wort „ehrenlos“ hörst?",
    "Wer ist die erste Person, an die du denkst, wenn du das Wort „bff“ hörst?",
    "Wer ist die erste Person, die dir bei dem Wort „sexy“ einfällt?",
    "Wer hat am wenigsten Zeit in Körperpflege investiert?",
    "Wer ernährt sich am ungesündesten?",
    "Welches Gemüse passt zu welcher Person hier?",
    "Welche Farbe gibst du jeder Person in der Runde?",
    "Welches Tier beschreibt jede Person in dieser Runde am besten?",
  ],
  dare: [
    "Was würdest du tun, wenn du für einen Tag unsichtbar wärst?",
    "Was würdest du tun, wenn du im Lotto gewinnst?",
    "Wen würdest du mit auf eine einsame Insel nehmen?",
    "Was würdest du machen, wenn du für einen Tag ein Mann oder eine Frau wärst?",
    "Was würdest du machen, wenn du für einen Tag unsichtbar wärst?",
    "Erzähle einen Witz - egal wie schlecht er ist.",
    "Tanze 30 Sekunden lang ohne Musik.",
    "Mache der Person links von dir ein ehrliches Kompliment.",
    "Sprich für die nächsten 3 Minuten nur in Reimen.",
    "Tausche für eine Runde deinen Platz mit jemandem.",
    "Poste ein Selfie mit deiner „hässlichsten“ Grimasse.",
    "Iss einen Löffel Senf/Ketchup o. Ä.",
    "Lass dich von jemandem aus der Runde schminken.",
    "Rufe jemanden an und sing ihm „Happy Birthday“ - egal ob er Geburtstag hat oder nicht.",
    "Stell eine peinliche Szene aus einem Film nach.",
    "Laufe wie ein Model durch den Raum.",
    "Erzähle deinen schlimmsten Witz.",
    "Lies die letzten drei Nachrichten in deinem Chatverlauf laut vor.",
    "Mache zehn Hampelmänner.",
    "Benutze für eine Runde nur deine Hände zum Sprechen.",
    "Lächle für zwei Minuten dauerhaft - egal was passiert.",
    "Lass dir von jemandem die Augen verbinden und beschreibe einen Gegenstand.",
    "Erfinde ein spontanes Lied über jemanden hier.",
    "Immitiere jemanden aus der Runde und die anderen müssen raten, wer es ist.",
    "Zeige dein letztes Foto auf deinem Handy.",
    "Flirte mit einem Gegenstand im Raum.",
    "Erkläre in 60 Sekunden, warum du der perfekte Superheld wärst.",
    "Lass jemanden einen peinlichen Spitznamen für dich aussuchen, den du für den Rest des Spiels trägst.",
    "Sprich in einer übertriebenen Synchronsprecher-Stimme für 3 Minuten.",
    "Lass dir von jemandem eine verrückte Frisur machen.",
    "Rufe deinen Ex-Partner an.",
    "Tanze öffentlich einen TikTok-Tanz.",
    "Rufe einen alten Freund an und verkaufe ihm eine Versicherung.",
    "Tausche mit dem Partner links von dir Outfits.",
    "Singe 30 Sekunden ein Lied mit Wasser im Mund.",
    "Küss deinen linken/rechten Nachbarn auf die Wange oder den Mund.",
    "Zeig uns deine Google-Suchhistorie.",
    "Imitiere einen brunftigen Hirsch.",
    "Tausche dein Oberteil mit dem Spieler links/rechts von dir.",
    "Leg dich in die Mitte, schlie ss die Augen und lass dich eine Minute lang von allen kitzeln.",
    "Trinke einen Shot (wenn du erwachsen bist).",
    "Mach 10 Liegestütze.",
    "Mach ein Selfie von der Gruppe und poste es auf Instagram/Facebook/Snapchat.",
    "Mach der Person links/rechts von dir ein ernstgemeintes Kompliment.",
    "Teste wessen Haare am besten riechen.",
    "Imitiere eine Person aus der Runde. Die anderen müssen erraten, wer es ist.",
    "Trink das Getränk von dem Spieler links/rechts von dir auf ex.",
    "Tanze 60 Sekunden sexy zu einem Lied.",
    "Beleidige die Person links/rechts von dir.",
    "Schick einer Person per Whatsapp ein Kompliment.",
    "Zeig allen ein peinliches Foto von dir.",
    "Zeig allen deine letzte Whatsapp.",
    "Zeig allen das letzte Foto, was du geschossen hast.",
    "Umarme die Person gegenüber so herzlich wie möglich.",
    "Flirte eine Runde mit der Person links/rechts von dir.",
    "Erzähl der Person gegenüber, was du besonders attraktiv an ihr findest.",
    "Schrei 20 schlimme Schimpfwörter.",
    "Nimm einen Eiswürfel und steck ihn dir in die Hose.",
    "Schick jemandem, der nicht mitspielt, ein Bild von deinen nackten Fü ssen.",
    "Schütte dir einen Drink ein, ohne die Hände zu benutzen.",
    "Ruf die fünftletzte Nummer, die du gewählt hast, an, frag die Person wie das folgende Lied hei sst und sing es ihr vor, bis sie den Titel nennt.",
    "Du bist für eine Runde der Butler. Achte darauf, dass alle Gäste immer genug zu trinken haben und behandle sie mit ausreichend Respekt.",
    "Du hast dich schlecht verhalten. Stell dich eine Runde in die Ecke und schäm dich.",
    "Lass einen Spieler an deiner Achsel riechen.",
    "Tausche dein T-Shirt mit der Person rechts neben dir.",
    "Gib deinem linken Nachbarn dein Handy und lass ihn in deine Foto-Galerie schauen.",
    "Lege einen Moonwalk wie Michael Jackson hin.",
    "Laufe wie bei Germany's Next Topmodel über den Catwalk.",
    "Jaule 30 Sekunden lang wie ein Wolf - ohne zu lachen!",
    "Spiele eine Szene aus deinem Lieblingsfilm nach.",
    "Mache einen Bauchtanz für die Gruppe.",
    "Gib jemandem in der Runde eine professionelle Massage.",
    "Tanze eine Minute lang wie ein Roboter.",
    "Trage deine Unterwäsche über deiner Hose für die nächsten zwei Runden.",
    "Iss einen Löffel voll Senf oder scharfer Sauce.",
    "Imitiere eine bekannte Persönlichkeit und lass die anderen erraten, wer du bist.",
    "Erzähle eine peinliche Geschichte aus deinem Leben.",
    "Mach einen Handstand gegen die Wand für mindestens 10 Sekunden.",
    "Führe einen Breakdance-Move vor.",
    "Mach einen Rückwärtssalto.",
    "Sing ein Lied rückwärts.",
    "Lass dir von jemandem in der Runde ein lustiges Gesicht schminken und trage es für den Rest des Spiels.",
    "Trinke einen Smoothie, der aus allen Zutaten besteht, die die Gruppe zusammenwirft.",
    "Versuche, dich selbst zu kitzeln, bis du lachst.",
    "Gib jemandem in der Runde eine Massage mit den Fü ssen.",
    "Mach einen Kopfstand für mindestens 30 Sekunden.",
    "Zeige der Gruppe deinen besten Zaubertrick.",
    "Tanze auf einem Bein für eine Minute.",
    "Gib einer Person in der Runde ein High-Five mit dem Fu ss.",
    "Mach einen Handstand und trinke ein Glas Wasser, ohne umzufallen.",
    "Lass dich von einer Person in der Runde schminken und trage das Ergebnis stolz.",
    "Mache einen Handstand und versuche, eine Runde zu laufen.",
    "Versuche, deinen Ellenbogen mit deiner Zunge zu berühren.",
    "Mache eine Yoga-Pose deiner Wahl für mindestens 30 Sekunden.",
    "Versuche, einen Apfel mit deinen Zähnen zu schälen.",
    "Mach einen Spagatversuch.",
    "Sing ein Lied mit vollem Mund.",
    "Trinke ein Glas Wasser, ohne deine Hände zu benutzen.",
    "Imitiere ein Tiergeräusch und lass die anderen raten, welches Tier es ist.",
    "Versuche, einen Purzelbaum zu machen.",
    "Tanze wie ein wildes Hühnchen für eine Minute.",
    "Versuche, deinen Daumen in den Mund zu stecken.",
    "Mache eine Standwaage für mindestens 20 Sekunden.",
    "Gib jemandem in der Runde eine Knuddelattacke.",
    "Stelle dich vor einen Spiegel und erfinde eine lustige Tanzroutine.",
    "Versuche, deinen Fu ss hinter deinen Kopf zu legen.",
    "Mach einen Handstand und versuche, ein Lied zu summen.",
    "Spiele eine Szene aus einem bekannten Theaterstück nach.",
    "Imitiere einen T-Rex und lasse die anderen lachen.",
    "Führe einen verrückten Tanz vor, den du dir spontan ausdenkst.",
    "Versuche, einen Salto rückwärts zu machen.",
    "Trinke ein Glas Wasser, während du dich auf den Händen abstützt.",
    "Mache eine Katzenpose und miaue laut.",
    "Gib jemandem in der Runde eine Bauchmassage.",
    "Mache einen Flickflack.",
    "Versuche, deine Zunge zu einer Rolle zu formen.",
    "Tanze wie ein Disco-König oder eine -Königin für eine Minute.",
    "Stelle dich auf die Zehenspitzen und bleibe so lange wie möglich in dieser Position.",
    "Imitiere einen Sumo-Ringer und lasse die anderen lachen.",
  ],
};

const dirty = {
  truth: [
    "Was ist deine geheimste Fantasie?",
    "Hattest du schon mal einen One-Night-Stand?",
    "Was war dein hei ssestes Erlebnis bisher?",
    "Mit wie vielen Personen hast du bereits geküsst?",
    "Was würdest du in einem Stripclub tun - zuschauen oder mitmachen?",
    "Hast du schon mal beim Flirten richtig übertrieben?",
    "Wo hast du schon mal etwas gemacht, das du lieber nicht erzählen willst?",
    "Was ist das Peinlichste, das dir beim Sex passiert ist?",
    "Hattest du schon mal Gefühle für jemanden, obwohl du vergeben warst?",
    "Mit wem hier würdest du eher eine Nacht verbringen als zuzugeben?",
    "Was würdest du mit deinem Crush tun, wenn ihr 24 Stunden allein wärt?",
    "Was ist dein Lieblingskörperteil - bei dir und bei anderen?",
    "Was ist deine Meinung zu Sexting?",
    "Hast du schon mal jemanden nur geküsst, um jemand anderen eifersüchtig zu machen?",
    "Was ist dein ultimativer Turn-on?",
    "Was darf in deinem Schlafzimmer niemals fehlen?",
    "Was war dein letzter „dirty“ Gedanke?",
    "Hast du schon mal einen erotischen Traum mit jemandem hier gehabt?",
    "Was war dein wildester Kussmoment?",
    "Welche Person hat dich zuletzt sexuell gereizt - sei ehrlich!",
    "Wurdest du schon mal beim „Erwischt-Werden“ fast erwischt?",
    "Welches Outfit findest du anziehend - bei dir oder bei anderen?",
    "Was war das Überraschendste, das du im Bett erlebt hast?",
    "Hast du schon mal bewusst mit jemandem gespielt - nur zum Spa ss?",
    "Was würdest du niemals im Bett tun - egal wie sehr du jemand liebst?",
    "Wie hoch ist dein Bodycount?",
    "Wie oft masturbierst du in der Woche?",
    "Wann hattest du das letzte Mal Sex?",
    "Mit wem hattest du das letzte Mal Sex?",
    "Wenn du mit einer Person in der Runde schlafen müsstest, wen würdest du auswählen?",
    "Wen in der Runde würdest du am ehesten küssen und warum?",
    "Hattest du schon mal einen Dreier?",
    "Hast du schon mal von einem Dreier geträumt?",
    "Wann hattest du deinen letzten feuchten Traum?",
    "Was war der verrückteste Ort, an dem du jemals Sex hattest?",
    "Wie oft hast du Sex?",
    "Wann hast du das letzte Mal masturbiert?",
    "Wie schafft man es am besten, dich zu erregen?",
    "Hast du schon mal mit jemandem aus der Runde geschlafen oder geknutscht?",
    "Welches Körperteil turnt dich am meisten an?",
    "Wen aus der Runde würdest du am liebsten nackt sehen wollen?",
    "Welche ist deine Lieblingsstellung?",
    "Wieso bist du gut im Bett?",
    "Wie kriegt man dich am besten rum?",
    "Mit wem hattest du bisher das beste Sex-Erlebnis deines Lebens?",
    "Hast du schon mal Nacktbilder verschickt?",
    "Gefällt dir Analsex?",
    "Bist du eher dominant oder devot?",
    "Welche Kleidung findest du besonders sexy an dir?",
    "Hast du schon mal jemanden gefesselt oder wurdest du schon mal gefesselt?",
    "Welches Pornogenre findest du am besten?",
    "Hast du ein Sexspielzeug?",
    "Wer ist hei sser? Hannes oder Jeremy?",
    "Mit wem hier hättest du den besten Sex?",
    "Was ist für dich die Altersober- und untergrenze für eine Person, mit der du ins Bett steigen würdest?",
    "Auf welchen Star hast du es dir schon mal selbst gemacht?",
    "Wer in deinem Umfeld hat dich mal unbewusst angeturnt?",
    "Hat dich schon mal ein Lehrer oder eine Lehrerin erregt? Wenn ja, wer?",
    "Wenn du keine Konsequenzen hättest - welchen Fetisch würdest du gerne ausprobieren?",
    "Hättest du etwas mit dem Elternteil deines Gegenübers gehabt, wenn dieser in deinem Alter gewesen wäre?",
    "Hast du dir jemals deine Eltern beim Sex vorgestellt?",
    "Hast du dir jemals deine Gro sseltern beim Sex vorgestellt?",
    "Hast du schon mal jemanden heimlich beim Duschen beobachtet?",
    "Hast du schon mal jemanden stöhnen gehört, den du lieber nicht gehört hättest? Wer war das?",
    "Hast du schon mal jemanden stöhnen gehört - und es dir daraufhin selbst gemacht?",
    "Hast du es dir schon mal auf dich selbst gemacht, also mit dir selbst als Fantasie?",
    "Was war der hei sseste Porno, den du je gesehen hast?",
    "Wurden dir beim Sex schon mal die Haare gezogen?",
    "Wen aus der Runde kannst du dir am wenigsten beim Sex vorstellen?",
    "Was würdest du tun, wenn du einen Tag lang das andere Geschlecht wärst?",
    "Welches Tier beschreibt jede Person in dieser Runde am besten?",
    "Wie viele Dates hattest du insgesamt über Dating-Apps?",
    "Wie viele dieser Dates haben zu Sex geführt?",
    "Bist du eher ein Bad Boy / eine Baddie - oder eher ein Sü ssi / eine Sü sse?",
  ],
  dare: [
    "Flüstere jemandem einen frechen Satz ins Ohr - so leise, dass nur er/sie es hört.",
    "Tanze 30 Sekunden lang verführerisch zu einem Song deiner Wahl.",
    "Beschreibe detailliert deinen letzten Kuss - oder erfinde ihn sehr glaubwürdig.",
    "Suche dir jemanden und halte 10 Sekunden lang intensiven Augenkontakt.",
    "Lecke spielerisch über deinen eigenen Finger - langsam.",
    "Sage drei anzügliche Sätze - als wärst du in einem Erotikfilm.",
    "Spiele eine Szene: Du versuchst jemanden in einer Bar zu verführen.",
    "Mache einem Mitspieler ein besonders hei sses Kompliment.",
    "Zeige der Runde dein „Ich bin in Versuchung“-Gesicht.",
    "Simuliere einen leidenschaftlichen Kuss - mit deiner Hand.",
    "Flirte mit einem Gegenstand in deiner Nähe, als wäre es eine hei sse Person.",
    "Nenne der Gruppe dein Lieblingskosewort - dann sag es langsam und hei ss.",
    "Gib der Person rechts von dir einen „sexy“ Spitznamen.",
    "Tanze mit einem Kissen - als wäre es dein Schwarm.",
    "Mache 3 verschiedene Arten, wie du jemanden begrü ssen würdest, wenn du ihn verführen willst.",
    "Flirte 30 Sekunden lang mit einer völlig unpassenden Sache (z. B. Wasserflasche, Fernbedienung).",
    "Erzähle einen kurzen erotischen Mini-Plot - komplett improvisiert.",
    "Zeige der Runde, wie du jemanden um den Finger wickelst - wortwörtlich.",
    "Lese einen Satz aus einem Erotikroman vor - mit Leidenschaft.",
    "Schreibe jemandem aus der Runde eine „verbotene“ Nachricht auf einen Zettel.",
    "Stelle ein „verbotenes“ Emoji-Pantomime-Rätsel.",
    "Sag etwas Nettes - aber so, als würdest du es flüstern wollen.",
    "Schicke einem Mitspieler ein Emoji - die anderen müssen erraten, was du sagen willst.",
    "Tu so, als würdest du ein Liebesgeständnis in eine Überwachungskamera machen.",
    "Nenne spontan drei Dinge, die dich in Stimmung bringen - ohne zu lachen.",
    "Renne nackt um den Block.",
    "Küsse die Person rechts von dir.",
  ],
};

const girlsnight = {
  truth: [
    "In wen warst du als Kind/Jugendliche heimlich verknallt?",
    "Was war dein schlimmstes Date ever?",
    "Welches Beauty-Fail hast du mal richtig bereut?",
    "Welcher Promi ist dein ultimativer Crush?",
    "Wem aus der Runde würdest du ein Tinder-Match gönnen?",
    "Was war das Verrückteste, was du je aus Liebeskummer getan hast?",
    "Hast du schon mal einen Schwarm gestalkt - online oder in echt?",
    "Wer wäre deine erste Wahl für einen Mädels-Urlaub?",
    "Was ist dein grö sster Mode-Fauxpas bisher gewesen?",
    "Hast du schon mal so getan, als wärst du vergeben, obwohl du es nicht warst?",
    "Was ist deine heimlichste Schwäche?",
    "Was denkst du über One-Night-Stands?",
    "Welcher Song beschreibt dein Liebesleben am besten?",
    "Was ist das Mutigste, das du dich je getraut hast in Sachen Liebe?",
    "Hast du schon mal jemandem etwas vorgespielt, nur um gut dazustehen?",
    "Mit welcher berühmten Person würdest du gerne einen Abend verbringen?",
    "Hast du schon mal jemanden geküsst, den du eigentlich nicht hättest küssen sollen?",
    "Welches Geheimnis hast du deiner besten Freundin noch nie erzählt?",
    "Würdest du eher einen Monat auf Make-up oder auf Social Media verzichten?",
    "Was findest du an dir selbst richtig sexy?",
    "Wem aus der Runde würdest du am ehesten dein Tagebuch anvertrauen?",
    "Hattest du schon mal einen peinlichen Moment beim Flirten?",
    "Was war dein wildester Mädelsabend?",
    "Was war dein schlimmster „Friendzone“-Moment?",
    "Hast du schon mal jemandem etwas vorgemacht, um nicht verletzt zu werden?",
  ],
  dare: [
    "Schminke dich in 2 Minuten - mit verbundenen Augen.",
    "Lies den letzten Chatverlauf mit deiner besten Freundin vor.",
    "Lass dir von jemandem aus der Runde die Haare frisieren - ganz egal wie!",
    "Poste ein Selfie mit dem Hashtag #GirlsNightUnfiltered (oder tue zumindest so).",
    "Tanze zu einem Boyband-Song so dramatisch wie möglich.",
    "Rufe eine Freundin an und sag ihr, dass du gerade auf einer heimlichen Mission bist.",
    "Mach ein Kompliment an jede Person in der Runde - ehrlich und kreativ.",
    "Schminke einer anderen Person mit deinem Lippenstift ein Herz auf die Wange.",
    "Zeig uns dein peinlichstes Lachen - und mach es nochmal lauter.",
    "Stell die Lieblingssängerin der Runde nach - mit Tanz und Gesang.",
    "Geh zu jemandem und sag: „Ich brauche deinen besten Liebestipp - sofort!“",
    "Schreibe jemandem eine Nachricht mit nur Emojis - die anderen bestimmen den Inhalt.",
    "Erfinde live einen Cocktailnamen und beschreibe, was drin ist.",
    "Mache eine kurze Modenschau mit einem komplett verrückten Outfit-Mix.",
    "Lass dich von zwei Personen gleichzeitig schminken - egal wie es aussieht.",
    "Sag der Person links von dir, was du am meisten an ihr bewunderst.",
    "Halte eine spontane Hochzeitsrede für deine „beste Freundin“. ",
    "Lass dich mit Decke oder Kissen zur „Königin der Nacht“ krönen - samt Pose.",
    "Sag einem Gegenstand in deiner Nähe, wie sehr du ihn liebst - mit Pathos!",
    "Lass dich fotografieren, während du dramatisch in die Ferne schaust.",
    "Singe laut einen Mädelsabend-Hit deiner Wahl - Playback oder echt!",
    "Tu so, als wärst du auf dem Laufsteg und beschreibe dein Outfit.",
    "Sage der Person gegenüber, was sie zu einer „Queen“ macht.",
    "Wickle dir ein Kleid aus einem Handtuch oder Schal - Laufsteg inklusive.",
    "Nimm das Handy so tief in den Mund wie du kannst.",
  ],
};

const hardcore = {
  truth: [
    "Was ist das Extremste, das du je im Bett erlebt hast?",
    "Hast du schon mal jemanden betrogen oder bist du betrogen worden?",
    "Wie oft denkst du an Sex - ehrlich?",
    "Was ist deine wildeste sexuelle Fantasie, die du niemals jemandem erzählt hast?",
    "Mit wie vielen Personen hattest du bereits Sex?",
    "Wo war der ungewöhnlichste Ort, an dem du es je getan hast?",
    "Was war dein peinlichster Orgasmus-Moment?",
    "Hast du schon mal zwei Personen gleichzeitig gedatet - ohne dass sie es wussten?",
    "Hattest du schon mal Sex an einem öffentlichen Ort?",
    "Gibt es ein Tabu, das du irgendwann brechen willst?",
    "Was würdest du für eine Nacht mit deinem Celebrity-Crush tun?",
    "Hattest du schon mal Lust auf jemanden, mit dem du eigentlich nichts anfangen dürftest?",
    "Hast du schon mal ein Nacktbild geschickt - oder bekommen?",
    "Was ist deine Meinung zu Dreier - schon erlebt oder Interesse?",
    "Welche Sextoy-Erfahrung hast du gemacht - oder würdest du gerne machen?",
    "Was war dein längster Entzug - und wie hast du's überstanden?",
    "Welche Szene aus einem Film findest du besonders anturnend?",
    "Welches Rollenspiel würdest du gerne mal ausprobieren?",
    "Wie oft hattest du schon Sex in einer Nacht?",
    "Was wäre ein absoluter Dealbreaker im Bett für dich?",
    "Mit wem aus deinem Umfeld könntest du dir theoretisch „mehr“ vorstellen?",
    "Hast du schon mal jemanden nur wegen seines Körpers gedatet?",
    "Was ist dein perversester Gedanke, den du je hattest?",
    "Würdest du eine offene Beziehung führen - und warum (nicht)?",
    "Gibt es ein Geheimnis, das du bisher niemandem erzählt hast, weil es zu krass ist?",
    "Wie lange hast du durchschnittlich Sex?",
    "Schon mal Analsex gehabt?",
    "Wer würde seine Familie am ehesten nie wiedersehen - für eine Million Euro?",
    "Was ist die objektiv schlimmste Sache, für die du einen Mord begehen würdest?",
    "Würdest du lieber 50 Millionen Euro bekommen oder die Klimakrise beenden?",
    "Wenn du keine Konsequenzen hättest - was würdest du mit der Person machen, die du am wenigsten auf der Welt magst?",
    "Wenn du keine Konsequenzen hättest - wen würdest du ermorden?",
    "Du hast 24 Stunden ohne Konsequenzen - was machst du?",
    "Welches Thema könntest du nicht ansprechen, ohne dass es Streit geben würde?",
    "Wer wird mit 30 am wenigsten Geld haben?",
    "Wem würdest du am wenigsten ein Geheimnis anvertrauen?",
  ],
  dare: [
    "Simuliere für 15 Sekunden einen echten Höhepunkt - so glaubwürdig wie möglich.",
    "Lies einen beliebigen Text so vor, als würdest du jemanden im Bett anmachen.",
    "Tu so, als wärst du auf einer Erotik-Hotline - 30 Sekunden lang.",
    "Lasse die Gruppe bestimmen, welche Körperstelle du leicht mit Eis berührst.",
    "Mache eine erotische Produkt-Werbung für ein völlig unpassendes Objekt.",
    "Rufe jemanden an und flüstere „Ich kann gerade nicht reden, es ist … hei ss hier.“",
    "Zeige, wie du jemanden verführst - nur mit Blicken und Körpersprache.",
    "Schicke jemandem aus der Runde einen frechen Emoji-Text - mit Augenzwinkern.",
    "Lass dir von der Runde ein „Kusspaket“ zusammenstellen (z. B. Stirn, Hand, Wange).",
    "Tanze langsam und sexy - zu einem Kinderlied.",
    "Beschreibe, wie du dich auf ein hei sses Date vorbereiten würdest - sehr bildhaft.",
    "Lass jemandem ein Kompliment über seine „körperlichen Vorzüge“ da.",
    "Zieh dir ein Kleidungsstück aus - oder tausche es gegen ein völlig anderes Accessoire.",
    "Schreibe ein erotisches Mini-Gedicht - in 30 Sekunden.",
    "Führe eine erotische Massage vor - an einem Kissen oder einer Person (nach Zustimmung).",
    "Nenne drei Dinge, die du im Bett mal ausprobieren würdest - ohne rot zu werden.",
    "Stell ein erotisches Emoji-Puzzle dar - die anderen müssen raten.",
    "Mach mit der Person gegenüber von dir rum.",
    "Lecke eine Frucht so, als wäre sie jemand, den du begehrst.",
    "Gib einer Person einen „Kosenamen“, der nicht jugendfrei ist.",
    "Zeige deine „Dirty Dance“-Moves - mit Requisit.",
    "Flirte 30 Sekunden mit einer völlig unpassenden Person (oder Gegenstand).",
    "Führe ein 1-Minuten-Solo-Striptease auf - mit Spa ss und Stil.",
    "Flüstere jemandem aus der Runde ins Ohr, was du wirklich gerne tun würdest - niemand sonst darf es hören.",
    "Mache eine erotische Szene nach - z. B. Titanic, Fifty Shades, o. Ä.",
    "Erfinde einen neuen Sex-Trend und erkläre ihn, als wärst du Sexpert:in.",
    "Ziehe vier Kleidungsstücke aus.",
    "Frag deine Ex nach einem Date.",
    "Stell dich in die Mitte, schlie ss deine Augen und lass dich von einem zufälligen Mitspieler küssen.",
    "Zeig deinen Mitspielern kurz deinen Po.",
    "Gib dem Spieler links/rechts von dir einen Kuss.",
    "Geh auf alle Viere und lass dir auf den Hintern hauen.",
    "Nimm einen Eiswürfel in den Mund und gib ihn dem Spieler links/rechts von dir in den Mund.",
    "Zeig der Person gegenüber ein sexy Bild von dir.",
    "Gib der Person links/rechts von dir einen Lapdance.",
    "Flüster der Person gegenüber etwas Hei sses ins Ohr.",
    "Erzähle allen von einer Sexphantasie.",
    "Küss der ersten Person des anderen Geschlechts rechts von dir zärtlich den Hals.",
    "Zieh einer Person die Hose aus, ohne deine Hände zu benutzen.",
    "Nimm deine Lieblingssexstellung ein und zeige sie den anderen.",
    "Leg dich in die Mitte, schlie ss deine Augen und lass dir von einem zufälligen Mitspieler den Bauch küssen.",
    "Twerke für eine Minute in der Mitte.",
    "Geh aus dem Raum, zieh deine Unterwäsche aus, deine Hose wieder an und komm zurück.",
    "Sag jedem in der Runde, was an ihm sexy ist.",
    "Schätze, wer in der Runde am besten im Bett ist und warum.",
    "Lass den Spieler links/rechts von dir etwas von deinem Hals lecken.",
    "Erzähle allen von dem besten Sex deines Lebens.",
    "Erzähle allen, wieso Sex mit dir ein besonderes Erlebnis ist.",
    "Bestimme einen Spieler, der dir einen Zungenkuss geben muss.",
    "Führe den perfekten Blowjob mit einem Gegenstand deiner Wahl vor.",
    "Lass dich von einer Person deiner Wahl auf den nackten Hintern küssen.",
    "Lass dich (sanft) von einer Person deiner Wahl mit einem Gürtel auspeitschen.",
    "Lass dir von deinem linken oder rechten Mitspieler einen Knutschfleck am Hals oder am Bauch verpassen.",
    "Such dir jemanden aus, den du eine Runde lang erotisch massieren musst.",
    "Trinke einen kleinen Schluck von allen Getränken deiner Mitspieler.",
    "Steh auf, dreh dich um, zieh dich bis auf deine Unterhose aus, anschlie ssend wieder an und dreh dich wieder um.",
    "Lass dir von einem Spieler deiner Wahl die Nippel lecken.",
    "Mach einen Dreier-Kuss mit der Person links und rechts von dir.",
    "Lass dir von einem Mitspieler deiner Wahl in die Hose fassen.",
    "Mache eine Instagram-Story, in der du Hannes und Jeremy für das Spiel dankst.",
  ],
};

const outside = {
  truth: [
    "Was war dein peinlichstes Erlebnis drau ssen?",
    "Hast du dich schon mal irgendwo im Freien verlaufen?",
    "Was war das Abenteuerlichste, das du drau ssen erlebt hast?",
    "Bist du schon mal heimlich nachts rausgeschlichen?",
    "Was war der verrückteste Ort, an dem du je eingeschlafen bist?",
    "Würdest du einen Tag lang ohne Handy drau ssen verbringen?",
    "Was ist dein Lieblingsort in der Natur?",
    "Was war dein unangenehmstes Erlebnis in der Öffentlichkeit?",
    "Hast du schon mal drau ssen etwas gemacht, das du bereust?",
    "Welche drei Dinge würdest du mitnehmen, wenn du im Wald übernachten müsstest?",
    "Hattest du schon mal drau ssen einen Flirt?",
    "Bist du schon mal in der Öffentlichkeit hingefallen?",
    "Was ist das Ungewöhnlichste, das du drau ssen je gesehen hast?",
    "Was würdest du tun, wenn du mitten im Wald ohne Empfang wärst?",
    "Hast du schon mal in der Natur übernachtet?",
    "Würdest du für 50 Euro in einen Springbrunnen springen?",
    "Was war dein letzter Ausflug ins Freie?",
    "Was war das Mutigste, das du jemals drau ssen getan hast?",
    "Welche Tierbegegnung war für dich am beängstigendsten?",
    "Was würdest du machen, wenn du im Park einen Schatz finden würdest?",
    "Hast du schon mal drau ssen etwas verloren, das dir wichtig war?",
    "Bist du eher Team Sonne oder Team Schnee?",
    "Würdest du eine Nacht im Zelt ohne Strom verbringen?",
    "Wann warst du das letzte Mal so richtig drau ssen unterwegs?",
    "Hast du schon mal unter freiem Himmel jemanden geküsst?",
  ],
  dare: [
    "Stell dich auf den Tisch und zähle von 10 runter ohne Grund.",
    "Laufe rückwärts bis zur nächsten Bank/Laterne/Markierung.",
    "Begrü sse einen Fremden mit einem High-Five.",
    "Mache 10 Liegestütze auf dem Rasen oder Gehweg.",
    "Baue aus Naturmaterialien eine kleine Skulptur.",
    "Führe für 1 Minute ein lautes Gespräch mit einem Baum.",
    "Rufe so laut du kannst: „Ich liebe [Name einer Person aus der Runde]!“",
    "Sammle in 2 Minuten 5 verschiedene Naturmaterialien (Blätter, Steine, etc.).",
    "Laufe barfu ss 30 Sekunden auf der Wiese oder dem Boden.",
    "Tanze zu einem Lied, das jemand anderes laut über sein Handy spielt.",
    "Springe in ein Gebüsch (ohne dich zu verletzen!).",
    "Immitiere einen Vogel für 30 Sekunden.",
    "Laufe im Kreis und tue so, als würdest du ein unsichtbares Haustier Gassi führen.",
    "Klatsche in die Hände, jedes Mal wenn jemand spricht - für eine ganze Runde.",
    "Baue ein Wettrennen gegen jemanden aus der Runde.",
    "Tue so, als würdest du joggen, aber mit einem sehr dramatischen Gesichtsausdruck.",
    "Lege dich auf den Boden und tue so, als würdest du Sterne zählen (auch tagsüber).",
    "Spreche Passanten auf ein völlig ausgedachtes Produkt an.",
    "Stelle dich wie ein Denkmal für 1 Minute komplett still hin.",
    "Hüpfe wie ein Frosch durch den Park/Bereich.",
    "Halte einem Vogel oder Insekt eine kleine Rede.",
    "Versuche, einen Papierflieger so weit wie möglich zu werfen.",
    "Finde einen lustigen Stock und tu so, als wäre es dein Mikrofon.",
    "Laufe wie ein Model über eine imaginäre Outdoor-Catwalk-Strecke.",
    "Male mit einem Stock oder deinem Finger ein Bild auf dem Boden.",
    "Gib einem Baum einen Namen und umarme ihn.",
    "Geh zu jemandem in der Stadt und tue so als ob er dich betrogen hat.",
    "Frage eine fremde Person, ob du morgen mit ihr frühstücken darfst.",
  ],
};
